Timesheet = Timesheet || new Object();
Timesheet.themes = Timesheet.themes || {};
Timesheet.themes.bootstrap = {
  'ReactTimesheet_settings': 'row',
  'ReactTimesheet_submit_settings': 'text-right',
  'ReactTimesheet_settings_btn': 'btn btn-default',
  'ReactTimesheet_container': 'row',
  'ReactTimesheet_docks': 'col-sm-4',
  'ReactTimesheet_times': 'col-sm-8',
  'ReactTimesheet_submit_row': 'row',
  'ReactTimesheet_submit_container': 'col-xs-12 text-right',
  'ReactTimesheet_submit_btn': 'btn btn-primary',
  'PartitionSelector_parts': 'progress',
  'PartitionSelector_bar': 'progress-bar',
  'ReactTimesheetTable_time_break': 'active',
  'ReactTimesheetTable_day': 'panel panel-default',
  'ReactTimesheetTable_day_name': 'panel-heading',
  'ReactTimesheetTable_day_panel': 'panel-collapse collapse in',
  'ReactTimesheetTable_day_table': 'table',
  'ReactTimesheetTable_time_input': 'form-control',
  'ReactTimesheetTable_name_input': 'form-control',
  'ReactTimesheetDock_types': 'nav nav-tabs dock-types',
  'ReactTimesheetDock_panel': 'list-group',
  'ReactTimesheetDock_search_item': 'list-group-item',
  'ReactTimesheetDock_search_input': 'form-control',
  'ReactTimesheetDock_label': 'list-group-item disabled',
  'ReactTimesheetDock_item': 'list-group-item dock-panel-item',
  'ReactTimesheetDock_item_text': 'list-group-item-text',
  'ReactTimesheetDock_item_value': 'label label-primary',
  'ReactTimesheetDock_item_badge': 'label label-default',
  'ReactTimesheetDock_loading': 'list-group',
  'ReactTimesheetDock_loading_item': 'list-group-item',
};
